#!/usr/bin/env nu
# Tests for run_onchange_after_02_linux-apt-install-nix-packages.nu
use std/assert

const SCRIPT_PATH = ".chezmoiscripts/run_onchange_after_02_linux-apt-install-nix-packages.nu"

def get-script-path [] {
    let chezmoi_root = $env.HOME | path join ".local" "share" "chezmoi"
    $chezmoi_root | path join $SCRIPT_PATH
}

def "test script parses" [] {
    let script = (get-script-path)
    let exit_code = (nu -n -c $"source ($script)" | complete | get exit_code)
    assert equal $exit_code 0
}

def "test generates user nix content" [] {
    let username = "testuser"
    let expected = $"# Generated by chezmoi script from system username\n{ username = \"($username)\"; }\n"

    # Test the user.nix generation logic
    let user_nix = $"# Generated by chezmoi script from system username\n{ username = \"($username)\"; }\n"
    assert equal $user_nix $expected
}

def "test uses env HOME" [] {
    # Verify the script references $env.HOME correctly
    let script = (get-script-path)
    let content = (open $script)
    assert str contains $content "$env.HOME"
}

def "test no chezmoi commands" [] {
    # Verify script doesn't call chezmoi (to avoid recursion)
    let script = (get-script-path)
    let content = (open $script)
    assert not ($content | str contains "chezmoi source-path")
    assert not ($content | str contains "chezmoi data")
}

def main [] {
    print "Running linux-apt-install-nix-packages.nu tests..."
    print ""

    test script parses
    print "✓ Script parses without errors"

    test generates user nix content
    print "✓ User.nix generation logic works"

    test uses env HOME
    print "✓ Script uses $env.HOME for paths"

    test no chezmoi commands
    print "✓ Script avoids chezmoi recursion"

    print ""
    print "✅ All tests passed!"
}
