{
  description = "NixOS configurations for multiple hosts";

  inputs = {
    # Stable 25.05 for NixOS
    nixpkgs.url = "github:nixos/nixpkgs/nixos-25.05";
    # Stable 25.05 for darwin (uses darwin-specific branch)
    nixpkgs-darwin.url = "github:NixOS/nixpkgs/nixpkgs-25.05-darwin";
    # Unstable available for select packages
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    nixos-hardware.url = "github:NixOS/nixos-hardware/master";

    # NixOS-WSL support
    nixos-wsl = {
      url = "github:nix-community/NixOS-WSL";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # nix-darwin support - use nix-darwin-25.05 branch
    nix-darwin = {
      url = "github:nix-darwin/nix-darwin/nix-darwin-25.05";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };

    nur.url = "github:nix-community/NUR";

    home-manager = {
      url = "github:nix-community/home-manager/release-25.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    claude-code-nix = {
      url = "github:sadjow/claude-code-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, nixpkgs-darwin, nixpkgs-unstable, nixos-hardware, nixos-wsl, nix-darwin, nur, home-manager, claude-code-nix, ... }@inputs:
    let
      # Username from user.nix (generated by justfile from chezmoi config)
      defaultUsername = (import ./user.nix).username;

      # Common overlays shared by all hosts
      commonOverlays = [
        nur.overlays.default
        (final: prev: {
          unstable = import nixpkgs-unstable {
            system = final.system;
            config.allowUnfree = true;
          };
          tmux-harpoon = final.callPackage ./pkgs/tmux-harpoon.nix { };
          tmux-tilish = final.callPackage ./pkgs/tmux-tilish.nix { };
          bitbucket-cli = final.callPackage ./pkgs/bitbucket-cli.nix { };
          zesh = final.callPackage ./pkgs/zesh.nix { };
        })
        claude-code-nix.overlays.default
      ];

      # Helper function to create a NixOS system
      # username defaults to defaultUsername but can be overridden per-config
      mkSystem = { hostname, system, modules, username ? defaultUsername }:
        let
          userConfig = { inherit username; };
        in
        nixpkgs.lib.nixosSystem {
          inherit system;
          modules = [
            { nixpkgs.overlays = commonOverlays; }
            { _module.args = { inherit inputs userConfig; }; }
          ] ++ modules;
          specialArgs = { inherit inputs; };
        };

      # Helper function to create a darwin system
      mkDarwin = { system, modules, username ? defaultUsername }:
        let
          userConfig = { inherit username; };
        in
        nix-darwin.lib.darwinSystem {
          inherit system;
          modules = [
            { nixpkgs.overlays = commonOverlays; }
          ] ++ modules;
          specialArgs = {
            inherit inputs userConfig;
            pkgs-unstable = import nixpkgs-unstable {
              inherit system;
              config.allowUnfree = true;
            };
          };
        };
    in
    {
      nixosConfigurations = {
        # dendrite - ThinkPad T470 portable workstation
        dendrite = mkSystem {
          hostname = "dendrite";
          system = "x86_64-linux";
          modules = [
            # Main configuration
            ./configuration.nix

            # Host-specific configuration
            ./hosts/dendrite/configuration.nix

            # Hardware configuration for ThinkPad T470
            nixos-hardware.nixosModules.lenovo-thinkpad-t470s
            nixos-hardware.nixosModules.common-cpu-intel
            nixos-hardware.nixosModules.common-pc-laptop
            nixos-hardware.nixosModules.common-pc-laptop-ssd
          ];
        };

        # mitosis - Virtual machine for testing and replication
        mitosis = mkSystem {
          hostname = "mitosis";
          system = "x86_64-linux";
          modules = [
            # Main configuration (shared)
            ./configuration.nix

            # VM-specific configuration
            ./hosts/mitosis/configuration.nix
          ];
        };

        # symbiont - NixOS on WSL (two systems coexisting)
        symbiont = mkSystem {
          hostname = "symbiont";
          system = "x86_64-linux";
          modules = [
            # NixOS-WSL base module (provides wsl.* options)
            nixos-wsl.nixosModules.default

            # Main configuration (shared)
            ./configuration.nix

            # WSL-specific configuration
            ./hosts/symbiont/configuration.nix
          ];
        };
      };

      # nix-darwin configurations
      darwinConfigurations = {
        # malus - macOS workstation (default user from user.nix)
        malus = mkDarwin {
          system = "aarch64-darwin";
          modules = [ ../darwin/hosts/malus/configuration.nix ];
        };

        # Example: malus with different user
        # malus-john = mkDarwin {
        #   system = "aarch64-darwin";
        #   modules = [ ../darwin/hosts/malus/configuration.nix ];
        #   username = "john";
        # };
      };
    };
}
