"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json"

[general]
allow_concurrent_presets = false

[defaults]
kanata_executable = "/usr/local/bin/kanata"
tcp_port = 5829
autorun = false

[presets.kinesis]
kanata_config = "~/.config/kanata/darwin.kbd"
autorun = true

[presets.laptop]
kanata_config = "~/.config/kanata/laptop.kbd"
