name: Nix Build
on:
  pull_request:
    branches: [main]
    paths:
      - "nix/**"
jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Evaluate flake outputs
        run: |
          nix eval --raw ./nix/nixos#packages.x86_64-linux.ribosome-env.drvPath
          nix eval --raw ./nix/nixos#darwinConfigurations.axon.config.system.build.toplevel.drvPath
