name: Validate
on:
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: devenv
      - name: Run checks
        run: nix run github:cachix/devenv/v2.1.2 -- shell -- prek run --from-ref origin/main --to-ref HEAD
